import type { Resource } from "./types";

export const resources: Resource[] = [
  // ── Apps/Tools (~12) ──────────────────────────────────────────────────
  {
    id: "tiimo",
    name: "Tiimo",
    communities: ["adhd", "autism"],
    problems: ["planning", "time-management"],
    urgency: "low",
    humanSupport: false,
    description: "Visual daily planner designed for neurodivergent brains with customizable routines and timers.",
    link: "https://www.tiimoapp.com",
    nextAction: "Download Tiimo and set up your first morning routine with 3–5 steps.",
  },
  {
    id: "todoist",
    name: "Todoist",
    communities: ["adhd", "student", "professional"],
    problems: ["task-initiation", "organization"],
    urgency: "low",
    humanSupport: false,
    description: "Task manager with natural-language input, projects, and priority levels to capture and organize to-dos.",
    link: "https://todoist.com",
    nextAction: "Create a Todoist account and do a brain dump of everything on your mind into the inbox.",
  },
  {
    id: "forest",
    name: "Forest",
    communities: ["adhd", "student"],
    problems: ["focus", "motivation"],
    urgency: "low",
    humanSupport: false,
    description: "Gamified focus timer that grows virtual trees when you stay off your phone.",
    link: "https://www.forestapp.cc",
    nextAction: "Install Forest and try one 25-minute focus session right now.",
  },
  {
    id: "brainfm",
    name: "Brain.fm",
    communities: ["adhd", "anxiety"],
    problems: ["focus", "sleep"],
    urgency: "low",
    humanSupport: false,
    description: "AI-generated functional music scientifically designed to improve focus, relaxation, and sleep.",
    link: "https://www.brain.fm",
    nextAction: "Start a free Brain.fm focus session and work on your most important task for 30 minutes.",
  },
  {
    id: "goblin-tools",
    name: "Goblin.tools",
    communities: ["adhd", "autism"],
    problems: ["task-initiation", "overwhelm"],
    urgency: "medium",
    humanSupport: false,
    description: "AI-powered tool that breaks vague or overwhelming tasks into small, concrete steps.",
    link: "https://goblin.tools",
    nextAction: "Paste your most dreaded task into the Magic To-Do tool and let it break it down for you.",
  },
  {
    id: "focusmate",
    name: "Focusmate",
    communities: ["adhd", "professional"],
    problems: ["task-initiation", "motivation"],
    urgency: "medium",
    humanSupport: true,
    description: "Virtual coworking platform that pairs you with an accountability partner for 25- or 50-minute sessions.",
    link: "https://www.focusmate.com",
    nextAction: "Sign up for Focusmate and book your first session within the next 2 hours.",
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    communities: ["dyslexia", "student", "professional"],
    problems: ["communication", "organization"],
    urgency: "low",
    humanSupport: false,
    description: "Real-time AI transcription for meetings, lectures, and conversations with searchable notes.",
    link: "https://otter.ai",
    nextAction: "Install Otter.ai and use it to transcribe your next meeting or lecture.",
  },
  {
    id: "calm",
    name: "Calm",
    communities: ["anxiety", "depression"],
    problems: ["sleep", "emotional-regulation"],
    urgency: "medium",
    humanSupport: false,
    description: "Meditation and sleep app with guided sessions, breathing exercises, and sleep stories.",
    link: "https://www.calm.com",
    nextAction: "Open Calm and complete the 7-minute 'Daily Calm' meditation right now.",
  },
  {
    id: "routinery",
    name: "Routinery",
    communities: ["adhd", "autism"],
    problems: ["time-management", "planning"],
    urgency: "low",
    humanSupport: false,
    description: "Step-by-step routine app with built-in timers that guides you through morning, evening, and custom routines.",
    link: "https://routinery.co",
    nextAction: "Download Routinery and build a 5-step morning routine with time estimates for each step.",
  },
  {
    id: "notion",
    name: "Notion",
    communities: ["student", "professional"],
    problems: ["organization", "planning"],
    urgency: "low",
    humanSupport: false,
    description: "All-in-one workspace for notes, databases, project management, and personal knowledge bases.",
    link: "https://www.notion.so",
    nextAction: "Create a free Notion account and set up a simple dashboard with your top 3 current projects.",
  },
  {
    id: "speechify",
    name: "Speechify",
    communities: ["dyslexia", "adhd"],
    problems: ["focus", "communication"],
    urgency: "low",
    humanSupport: false,
    description: "Text-to-speech reader that converts articles, PDFs, and documents into natural-sounding audio.",
    link: "https://speechify.com",
    nextAction: "Install the Speechify browser extension and listen to an article you've been putting off reading.",
  },
  {
    id: "mightier",
    name: "Mightier",
    communities: ["parent", "autism"],
    problems: ["emotional-regulation", "sensory"],
    urgency: "medium",
    humanSupport: false,
    description: "Biofeedback gaming platform that teaches kids emotional regulation through heart-rate-connected games.",
    link: "https://www.mightier.com",
    nextAction: "Visit the Mightier website and sign up for a starter kit to try with your child.",
  },

  // ── Communities/Platforms (~8) ────────────────────────────────────────
  {
    id: "chadd",
    name: "CHADD",
    communities: ["adhd", "parent"],
    problems: ["planning", "organization"],
    urgency: "low",
    humanSupport: true,
    description: "National ADHD organization offering support groups, webinars, and an expert directory.",
    link: "https://chadd.org",
    nextAction: "Find your nearest CHADD support group on their website and register for the next meeting.",
  },
  {
    id: "understood",
    name: "Understood.org",
    communities: ["dyslexia", "adhd", "parent"],
    problems: ["communication", "planning"],
    urgency: "low",
    humanSupport: false,
    description: "Comprehensive resource hub for learning and thinking differences with expert-backed articles and tools.",
    link: "https://www.understood.org",
    nextAction: "Take the free 'Through Your Child's Eyes' simulation on Understood.org to build empathy and insight.",
  },
  {
    id: "additude",
    name: "ADDitude Magazine",
    communities: ["adhd", "parent"],
    problems: ["focus", "time-management", "organization"],
    urgency: "low",
    humanSupport: false,
    description: "Leading ADHD publication with expert articles, webinars, and downloadable guides on managing ADHD.",
    link: "https://www.additudemag.com",
    nextAction: "Subscribe to the free ADDitude newsletter and read their top-rated article on your biggest challenge.",
  },
  {
    id: "wrong-planet",
    name: "Wrong Planet",
    communities: ["autism"],
    problems: ["social", "communication"],
    urgency: "low",
    humanSupport: true,
    description: "Online community and forum for autistic individuals to discuss experiences, challenges, and interests.",
    link: "https://wrongplanet.net",
    nextAction: "Create a Wrong Planet account and introduce yourself in the General Discussion forum.",
  },
  {
    id: "how-to-adhd",
    name: "How to ADHD",
    communities: ["adhd"],
    problems: ["motivation", "task-initiation", "overwhelm"],
    urgency: "low",
    humanSupport: false,
    description: "YouTube channel with friendly, evidence-based videos on practical ADHD strategies and self-understanding.",
    link: "https://www.youtube.com/@HowtoADHD",
    nextAction: "Watch the 'How to Get Stuff Done When You Have ADHD' video and try one tip today.",
  },
  {
    id: "asan",
    name: "Autistic Self Advocacy Network",
    communities: ["autism"],
    problems: ["social", "communication"],
    urgency: "low",
    humanSupport: true,
    description: "Advocacy organization run by and for autistic people, providing policy resources and community connections.",
    link: "https://autisticadvocacy.org",
    nextAction: "Explore ASAN's resource library and share one article with someone who supports you.",
  },
  {
    id: "yale-dyslexia",
    name: "Yale Center for Dyslexia & Creativity",
    communities: ["dyslexia", "parent"],
    problems: ["communication", "organization"],
    urgency: "low",
    humanSupport: false,
    description: "Research-backed resources on dyslexia identification, accommodations, and strengths-based approaches.",
    link: "https://dyslexia.yale.edu",
    nextAction: "Read Yale's 'Signs of Dyslexia' page and note which signs resonate with your experience.",
  },
  {
    id: "nami",
    name: "NAMI",
    communities: ["anxiety", "depression"],
    problems: ["emotional-regulation", "social"],
    urgency: "medium",
    humanSupport: true,
    description: "National Alliance on Mental Illness offering free support groups, education programs, and a helpline.",
    link: "https://www.nami.org",
    nextAction: "Call the NAMI Helpline at 1-800-950-NAMI to find local support groups and resources.",
  },

  // ── Professional (~5) ────────────────────────────────────────────────
  {
    id: "betterhelp",
    name: "BetterHelp",
    communities: ["anxiety", "depression"],
    problems: ["emotional-regulation", "overwhelm"],
    urgency: "high",
    humanSupport: true,
    description: "Online therapy platform matching you with licensed therapists for text, phone, or video sessions.",
    link: "https://www.betterhelp.com",
    nextAction: "Complete the BetterHelp intake questionnaire to get matched with a therapist today.",
  },
  {
    id: "headway",
    name: "Headway",
    communities: ["anxiety", "depression", "adhd"],
    problems: ["emotional-regulation", "focus"],
    urgency: "high",
    humanSupport: true,
    description: "Platform that helps you find in-network therapists and psychiatrists who accept your insurance.",
    link: "https://headway.co",
    nextAction: "Enter your insurance details on Headway to see available therapists near you and book a session.",
  },
  {
    id: "adda-coaches",
    name: "ADDA Coaches",
    communities: ["adhd", "professional"],
    problems: ["planning", "time-management", "organization"],
    urgency: "medium",
    humanSupport: true,
    description: "Directory of certified ADHD coaches through the Attention Deficit Disorder Association.",
    link: "https://add.org/professional-directory",
    nextAction: "Browse the ADDA directory, filter by your needs, and contact one coach for a free consultation.",
  },
  {
    id: "sensory-owl",
    name: "Sensory Owl",
    communities: ["autism", "parent"],
    problems: ["sensory", "emotional-regulation"],
    urgency: "medium",
    humanSupport: false,
    description: "Curated sensory tools and products designed by occupational therapists for sensory processing needs.",
    link: "https://www.sensoryowl.com",
    nextAction: "Take the Sensory Owl quiz to identify your sensory profile and get personalized product recommendations.",
  },
  {
    id: "headspace",
    name: "Headspace",
    communities: ["anxiety", "student"],
    problems: ["focus", "sleep", "emotional-regulation"],
    urgency: "medium",
    humanSupport: false,
    description: "Guided mindfulness and meditation app with courses for stress, focus, sleep, and emotional well-being.",
    link: "https://www.headspace.com",
    nextAction: "Download Headspace and complete the free 'Basics' course — just 3 minutes for your first session.",
  },

  // ── Crisis (~4) ──────────────────────────────────────────────────────
  {
    id: "crisis-text-line",
    name: "Crisis Text Line",
    communities: ["anxiety", "depression", "student"],
    problems: ["emotional-regulation", "overwhelm"],
    urgency: "crisis",
    humanSupport: true,
    description: "Free 24/7 text-based crisis support — text HOME to 741741 to connect with a trained counselor.",
    link: "https://www.crisistextline.org",
    nextAction: "Text HOME to 741741 right now to connect with a crisis counselor.",
  },
  {
    id: "988-lifeline",
    name: "988 Suicide & Crisis Lifeline",
    communities: ["anxiety", "depression"],
    problems: ["emotional-regulation", "overwhelm"],
    urgency: "crisis",
    humanSupport: true,
    description: "Free 24/7 phone and chat support for anyone in suicidal crisis or emotional distress — call or text 988.",
    link: "https://988lifeline.org",
    nextAction: "Call or text 988 now to speak with a trained crisis counselor immediately.",
  },
  {
    id: "samhsa",
    name: "SAMHSA National Helpline",
    communities: ["depression", "anxiety"],
    problems: ["overwhelm", "emotional-regulation"],
    urgency: "crisis",
    humanSupport: true,
    description: "Free 24/7 treatment referral service for mental health and substance use disorders — call 1-800-662-4357.",
    link: "https://www.samhsa.gov/find-help/national-helpline",
    nextAction: "Call 1-800-662-4357 to get a free referral to local treatment and support services.",
  },
  {
    id: "trevor-project",
    name: "The Trevor Project",
    communities: ["student", "depression"],
    problems: ["emotional-regulation", "social"],
    urgency: "crisis",
    humanSupport: true,
    description: "24/7 crisis intervention and suicide prevention for LGBTQ+ young people — call, text, or chat.",
    link: "https://www.thetrevorproject.org",
    nextAction: "Call 1-866-488-7386 or text START to 678-678 to reach a Trevor counselor now.",
  },

  // ── Educational/Technique (~3) ───────────────────────────────────────
  {
    id: "pomodoro",
    name: "Pomodoro Technique",
    communities: ["adhd", "student"],
    problems: ["focus", "time-management"],
    urgency: "low",
    humanSupport: false,
    description: "Time management method using 25-minute focused work intervals followed by 5-minute breaks.",
    link: "https://todoist.com/productivity-methods/pomodoro-technique",
    nextAction: "Set a timer for 25 minutes, pick one task, and work on only that until the timer rings.",
  },
  {
    id: "body-doubling",
    name: "Body Doubling Guide",
    communities: ["adhd"],
    problems: ["task-initiation", "motivation"],
    urgency: "medium",
    humanSupport: true,
    description: "Technique of working alongside another person (in-person or virtually) to boost accountability and focus.",
    link: "https://add.org/the-body-double",
    nextAction: "Ask a friend to sit with you (or join Focusmate) while you tackle a task you've been avoiding.",
  },
  {
    id: "time-blocking",
    name: "Time Blocking Method",
    communities: ["adhd", "professional", "student"],
    problems: ["planning", "time-management", "organization"],
    urgency: "low",
    humanSupport: false,
    description: "Scheduling method where every hour of your day is assigned a specific task or activity in advance.",
    link: "https://todoist.com/productivity-methods/time-blocking",
    nextAction: "Block out tomorrow's calendar in 30-minute chunks, assigning your top 3 priorities to morning slots.",
  },
];
